# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RSSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SnapKit'
	pod 'FeedKit'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RxDataSources'
  pod 'Kingfisher'

  target 'RSSExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RSSExampleUITests' do
    # Pods for testing
  end

end
